// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvN5ZXEkZFge8SaweS2rg2BO0I41sFJvQ',
    appId: '1:665951552633:web:77d798e27d0dd09d0b80a8',
    messagingSenderId: '665951552633',
    projectId: 'clubmanagement-9806c',
    authDomain: 'clubmanagement-9806c.firebaseapp.com',
    storageBucket: 'clubmanagement-9806c.firebasestorage.app',
    measurementId: 'G-C1QBG8S2SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9Hgdgp3bE_Q7-9hOmK2KDsc2PbVky1Y',
    appId: '1:665951552633:android:b44fdbed8ab846fb0b80a8',
    messagingSenderId: '665951552633',
    projectId: 'clubmanagement-9806c',
    storageBucket: 'clubmanagement-9806c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv-1E5CP4LDME-ZOIMX9v9La1LF7LfWgs',
    appId: '1:665951552633:ios:22e698b16cbaa7e20b80a8',
    messagingSenderId: '665951552633',
    projectId: 'clubmanagement-9806c',
    storageBucket: 'clubmanagement-9806c.firebasestorage.app',
    iosBundleId: 'com.clubmanagement.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo-macos-key-replace-with-actual',
    appId: '1:123456789:macos:demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'club-management-demo',
    storageBucket: 'club-management-demo.appspot.com',
    iosBundleId: 'com.example.clubManagement',
  );
}